### ISSUE TITLE
Dev Lead/ Product Manager for https://mitosis.pictures/

### ISSUE THREAD

**Issue by breck7** [breck7/CancerDB#9]
A website with pictures of mitosis. Who wants to lead?

**Comment by adriantintpilver** [comment]
Hi Breck, The site https://mitosis.pictures/ doesn't work. 
What do you need in this issue? Do you need to make this site? or fix this site? 
Please tell me.

**Comment by breck7** [comment]
Hi @adriantintpilver mitosis.pictures is a "blue ocean" project—someone should start it from scratch. All I have is the domain. I want a site that just has lots of pictures and videos of mitosis (cell division). People should be able to go there and just learn about mitosis from looking at the pictures and videos. There should be no words (well, maybe there should be captions/links to the sources of the photos, but it should really be a visual site).

**Comment by adriantintpilver** [comment]
Hi Breck,

I understand, it is very interesting to develop something from scratch.
Do you have any idea what to use for this? any open source of Nodejs?

Thanks!

**Comment by breck7** [comment]
Whatever you want @adriantintpilver! I obviously love NodeJs, but if you wanted to use GoLang or Elixir or Rust or something else, that would be fine too.

**Comment by adriantintpilver** [comment]
ok, i don't know a good template for a visual site as you say. I will research what options are and tell you later.

**Comment by ege-del** [comment]
I would like to contribute as well. I couldn't find any good templates, but I can write it from scratch with NodeJs and Bootstrap.
maybe something like this ? 
https://lordeys.com/shanghai/country/cn/assets/leung/website-desktop-gallery-artworks.jpg

**Comment by adriantintpilver** [comment]
Hi @breck7,

I was evaluating some options, and I put together this one that seems very good to me, it is very fast visually. I took the liberty of uploading it to an AWS instance so that you can see it working and I uploaded some content of the topic that I found on the internet.
In the home leave an image title and some lines of description and then when entering you have everything.
It is developed in Nodejs and a mongoDB.

You can see it working at http://ec2-18-231-183-66.sa-east-1.compute.amazonaws.com/.
I'll keep the instant on until you see it.
For now it is sorted by date of when it was uploaded and shows that data.
You can try to upload something new with the upload button.

The repo where I uploaded this is: https://github.com/adriantintpilver/Visual-CancerDB
The code is still a bit dirty, and he didn't want to upload it to yours until he knew we're on the right track.

Please, I await your comments.

Thank you so much!
Regards!

**Comment by celtic-coder** [comment]
Hi Adrian (@adriantintpilver),

Does the hamburger menu open up other options?

Kind Regards,
Liam

**Comment by adriantintpilver** [comment]
Hi Liam,

I haven't included the menu yet, just wanted to check at this point if the page looks fine before I go ahead and add more options.
If you like this design, I`ll start working on the next step. I would really appreciate if you could send me some of the real contents you have. This way i can check several things such as how long the texts are, if there is a cover image for each case and some other additional images of the same subject, if there are related pathologies that we have to link between them.
Sorry for my lack of knowledge on the subject, it would be very positive to have a little understanding in order to see what features to add.

Thanks and Regards!

**Comment by breck7** [comment]
Looks great @adriantintpilver ! I would ditch the animations. Too slow. We can always add animations later on when it's more mature.

**Comment by adriantintpilver** [comment]
Hi Breck, 

So we're going in the right way. 
I´ll go ahead with the hamburger menu and a search field that filters the images.
It would be great if you could provide me with some real data that you have in order to understand the data model and move forward on how the data is related. 
I'll see what I can do with the animation. 

Thank you and Regards

**Comment by ege-del** [comment]
I think @adriantintpilver provided a good starting point, lets transfer the repo - since @breck7 will be hosting it - then I can maybe PR some improvements and also images.

**Comment by adriantintpilver** [comment]
Hi! yes this is the idea, i never did something like that, but i am going to the github "danger zone" and try to do the transfer owner to @breck7 .

I'm working on the search right now, I think I'll finish today. When I finish that, i commit the changes and transfer the repo owner.

**Comment by adriantintpilver** [comment]
Hello guys!!

i commit some changes:

-. End of animations
-. Search field in the header and its functionality (search in title and description)
-. Initial README file.

@breck7 i also transferred the repo, this is pending your approval of this transfer Breck.

Due to the fact that for now we do not have hosting for this. i up an AWS instance again so that it can be seen and it is at --> http://ec2-18-230-108-113.sa-east-1.compute.amazonaws.com/ , leave it ON for a few days so they can test it.

I'm not sure if we will have categories and/or types of cancer for a parametric search, if so that would be something to add.
I'l like to take a look for the data and define the data model.

I'll keep moving forward with the Hamburger Menu.
Please wait for your comments.

Thanks and Regards!

**Comment by breck7** [comment]
Hi @adriantintpilver you can keep the repo under yours. Does not need to be under mine. Thanks!

**Comment by adriantintpilver** [comment]
Hi @breck7 !

I saw that @ege-del is already passing me content and corrections so we're making progress and that's great.

Do you have any solution in mind for the production hosting of this site? I don't know how you handle yourself in this aspect usually.

Thank you so much!
Regards!

**Comment by breck7** [comment]
New domain is: mitosispictures.com

**Comment by ege-del** [comment]
@breck7 we need third opinion on a design decision
https://github.com/adriantintpilver/Visual-CancerDB/pull/10

**Comment by breck7** [comment]
This is the new repo for this issue: https://github.com/breck7/mitosispictures.com

**Comment by breck7** [comment]
Where in the world are the `pictures of mitosis`? Was any work done on the core part of this task?

**Comment by breck7** [comment]
Sorry all, I wasn't paying much attention to what was happening here.

All we need is pictures of mitosis. Pngs and gifs and maybe some youtubes. That's it.

Sorry, this is my fault. I wasn't paying close attention and didn't realize that time was going in to code. We don't need any code here .

**Comment by breck7** [comment]
Reassigned

**Comment by ege-del** [comment]
I'm collecting pictures and videos here; https://github.com/ege-del/bio-db/blob/main/media/mitosis.json
I'll add more images soon.

**Comment by breck7** [comment]
Amazing work @ege-del !

V1 is live! http://public.mitosispictures.com/

**Comment by celtic-coder** [comment]
Great work @ege-del! 👍 

Just one small item. The YT link for the "[Animal Cell Mitosis](https://github.com/breck7/mitosispictures.com/blob/main/animal-cell-mitossi.scroll)" looks to be broken.
